[package]
name = "for-android"
version = "0.1.0"
authors = ["wws <1274704958@qq.com>"]
edition = "2018"

[dependencies]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.10", default-features = false }
android_logger = "0.5"

[lib]
crate_type = ["cdylib"]
