[package]
edition = "2018"
name = "min-test-rust"
version = "0.1.0"
authors = ["wusj7856 <wusj@realbull.net>"]

[dependencies]
test1 = { path="./test1"}
pm2 = {path="./pm2"}
encryption = {path="./encryption"}

[[example]]
name = "t_pm2"
path = "src/t_pm2.rs"